#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-base-perf
#@DESCRIPTION: Qualcomm Technologies, Inc. Base Linux Distribution (glibc based)
# with performance orientation. Serial console and a few debug features in base line
# distro are disabled. Uses a kernel config targeting faster bootup and performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-perf
#  * qti-distro-base-perf
#
# For same variable override precedence order is
# qti-distro-base-perf > qti-distro-perf > qti-distro-base
#######################################################################################

# Honor qti-distro-perf override
DISTROOVERRIDES =. "qti-distro-perf:"

require conf/distro/include/qti-distro-base.inc

DISTRO_NAME = "QTI Linux distro targeting performance builds."

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

# Allow tasks to run even if setscene is missing
BB_SETSCENE_ENFORCE = "0"

# Enable SELinux bits only when selinux is active in DISTRO_FEATURES
DISTRO_FEATURES_FILTER_NATIVE:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'selinux', ' selinux', '', d)}"
DISTRO_EXTRA_RDEPENDS:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'selinux', ' packagegroup-selinux-minimal', '', d)}"
PREFERRED_PROVIDER_virtual/refpolicy = " ${@bb.utils.contains('DISTRO_FEATURES', 'selinux', ' refpolicy-mls-generic', '', d)}"
