#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-host-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Base Linux Distribution (glibc based)
# with debugging capabilities. Not optimized for performance. Allows root user access.
#
#######################################################################################

require conf/distro/include/qti-distro-host.inc

DISTRO_NAME = "QTI Linux distro with debug capabilities."

