#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-eap-perf
#@DESCRIPTION: Qualcomm Technologies, Inc. External AP Linux Distribution
# (glibc based) with performance orientation. Serial console and a few debug features in
# base line distro are disabled. Uses a kernel config targeting faster bootup and performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-perf
#  * qti-distro-teleap
#  * qti-distro-teleap-perf
#
# For same variable override precedence order is
# qti-distro-teleap-perf > qti-distro-teleap > qti-distro-perf > qti-distro-base
#######################################################################################

# Honor qti-distro-perf override
DISTROOVERRIDES =. "qti-distro-perf:qti-distro-teleap:"

require conf/distro/include/qti-distro-teleap.inc

DISTRO_NAME = "QTI Linux External AP distro targeting performance builds."
