#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-xr-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Reference Linux Distribution
# (glibc based) for extended reality having debugging capabilities. Not optimized for
# performance. Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-xr-debug
#
# For same variable override precedence order is
# qti-distro-xr-debug > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:"

require conf/distro/include/qti-distro-xr.inc

DISTRO_NAME = "QTI Linux reference extended reality distro with debug capabilities."

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"
DISTRO_EXTRA_RDEPENDS += "packagegroup-selinux-minimal"
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls-xr"

#enable systemd journal
SYSTEMD_ENABLE_JOURNAL = "1"
