#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-vnm-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Full Reference Stack Linux Distribution
# (glibc based) having debugging capabilities. Not optimized for performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-vnm-debug
#
# For same variable override precedence order is
# qti-distro-vnm-debug > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:"

require conf/distro/include/qti-distro-fullstack.inc

DISTRO_NAME = "QTI Linux reference stack distro for voice and music with debug capabilities."

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

DISTRO_EXTRA_RDEPENDS += "packagegroup-selinux-minimal"
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls-robotics"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

#enable systemd journal
SYSTEMD_ENABLE_JOURNAL = "1"
