#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-base-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Base Linux Distribution (glibc based)
# with debugging capabilities. Not optimized for performance. Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-base-debug
#
# For same variable override precedence order is
# qti-distro-base-debug > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:"

require conf/distro/include/qti-distro-base.inc

DISTRO_NAME = "QTI Linux distro with debug capabilities."

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

#enable systemd journal
SYSTEMD_ENABLE_JOURNAL = "1"
# enabling SElinux configuration to support refpolicy-mls-generic bitbake
DISTRO_FEATURES_FILTER_NATIVE += " selinux "
DISTRO_EXTRA_RDEPENDS += "packagegroup-selinux-minimal"
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls-generic"
