#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-tele-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Telematics Linux Distribution
# (glibc based) having debugging capabilities. Not optimized for performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-tele
#  * qti-distro-tele-debug
#
# For same variable override precedence order is
# qti-distro-tele-debug > qti-distro-tele > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:qti-distro-tele:"

require conf/distro/include/qti-distro-tele.inc

DISTRO_NAME = "QTI Linux Telematics distro with debug capabilities."

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

#enable systemd journal
SYSTEMD_ENABLE_JOURNAL = "1"
