#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-tele-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Telematics NAD-Core Linux Distribution
# (glibc based) having debugging capabilities. Not optimized for performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-tele
#  * qti-distro-tele-nad
#  * qti-distro-tele-nad-debug
#
# For same variable override precedence order is
# qti-distro-tele-nad-debug > qti-distro-tele-nad > qti-distro-tele > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:qti-distro-tele:qti-distro-tele-nad:"

# NAD-Core specific distros are defined here
require conf/distro/include/qti-distro-tele-nad.inc

DISTRO_NAME = "QTI Linux Telematics NAD distro with debug capabilities."

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"
