#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-rb-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Full Reference Stack Linux Distribution
# (glibc based) having debugging capabilities. Not optimized for performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-fullstack-debug
#  * qti-distro-rb-debug
#
# For same variable override precedence order is
# qti-distro-rb-debug > qti-distro-fullstack-debug > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:"

require conf/distro/include/qti-distro-fullstack.inc

DISTRO_NAME = "QTI Linux robotics platform distro with debug capabilities."

# Enable imu client
# DISTRO_FEATURES += "imu-client"

# Enable ros2
DISTRO_FEATURES += "ros2"

# Enable qti-gst-ros2
# DISTRO_FEATURES += "qti-gst-ros2"

# Enable virtualization
DISTRO_FEATURES += "virtualization seccomp"

# Enable RealSense camera solution
DISTRO_FEATURES += "librealsense2"

#Enable vSLAM
DISTRO_FEATURES += "vslam"

#Enable QTI DFS
# DISTRO_FEATURES += "qti-dfs"

#Enable IB2C
DISTRO_FEATURES += "qti-ib2c"

#Enable UVC
DISTRO_FEATURES += "qti-uvc"

#Enable vulkan
DISTRO_FEATURES += "vulkan"

#Enable lxc
DISTRO_FEATURES += "lxc"

DISTRO_EXTRA_RDEPENDS += "packagegroup-selinux-minimal"
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls-robotics"

DISTRO_FEATURES:remove = " \
        dm-verity \
        fbdev \
        qti-security \
        qwesd \
"

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

#enable systemd journal
SYSTEMD_ENABLE_JOURNAL = "1"
