#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-tele-perf
#@DESCRIPTION: Qualcomm Technologies, Inc. Telematics Linux Distribution (glibc based)
# with performance orientation. Few debug features in base line distro are disabled.
# Uses a kernel config targeting faster bootup and performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-perf
#  * qti-distro-tele
#  * qti-distro-tele-perf
#
# For same variable override precedence order is
# qti-distro-tele-perf > qti-distro-tele > qti-distro-perf > qti-distro-base
#######################################################################################

# Honor qti-distro-perf override
DISTROOVERRIDES =. "qti-distro-perf:qti-distro-tele:"

require conf/distro/include/qti-distro-tele.inc

DISTRO_NAME = "QTI Linux Telematics distro targeting performance builds."
