#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-tele-nad-perf
#@DESCRIPTION: Qualcomm Technologies, Inc. Telematics NAD-Core Linux Distribution (glibc based)
# with performance orientation. Few debug features in base line distro are disabled.
# Uses a kernel config targeting faster bootup and performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-perf
#  * qti-distro-tele
#  * qti-distro-tele-nad
#  * qti-distro-tele-nad-perf
#
# For same variable override precedence order is
# qti-distro-tele-nad-perf > qti-distro-tele-nad > qti-distro-tele > qti-distro-perf > qti-distro-base
#######################################################################################

# Honor qti-distro-perf override
DISTROOVERRIDES =. "qti-distro-perf:qti-distro-tele:qti-distro-tele-nad:"

# NAD Core specific distros are defined here
require conf/distro/include/qti-distro-tele-nad.inc

DISTRO_NAME = "QTI Linux Telematics NAD distro targeting performance builds."
