#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-base-nosecurity-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Base Linux Distribution (glibc based)
# with debugging capabilities. Not optimized for performance. Allows root user access.
# no security fetures are available.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-base-nosecurity-debug
#
# For same variable override qti-distro-base-nosecurity-debug takes precedence over qti-distro-base.
#######################################################################################

require conf/distro/include/qti-distro-base.inc

DISTRO_NAME = "QTI Linux distro targeting basic debug builds without security features"

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

DISTRO_FEATURES_remove = "dm-verity"
DISTRO_FEATURES_remove = "selinux"
