#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-base-perf
#@DESCRIPTION: Qualcomm Technologies, Inc. Base Linux Distribution (glibc based)
# with performance orientation. Serial console and a few debug features in base line
# distro are disabled. Uses a kernel config targeting faster bootup and performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-perf
#  * qti-distro-base-perf
#
# For same variable override precedence order is
# qti-distro-base-perf > qti-distro-perf > qti-distro-base
#######################################################################################

# Honor qti-distro-perf override
DISTROOVERRIDES =. "qti-distro-perf:"

require conf/distro/include/qti-distro-base.inc

DISTRO_NAME = "QTI Linux distro targeting performance builds."

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"

# enabling SElinux configuration to support refpolicy-mls-generic bitbake
DISTRO_FEATURES_FILTER_NATIVE += " selinux "
DISTRO_EXTRA_RDEPENDS += "packagegroup-selinux-minimal"
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls-generic"
