#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-base-user
#@DESCRIPTION: Qualcomm Technologies, Inc. Base Linux Distribution (glibc based)
# with performance and security orientation. Serial console and other debug features in base
# line distro are disabled. Uses a kernel config targeting faster bootup and performance.
# Also root user privileges are disabled.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-user
#  * qti-distro-base-user
#
# For same variable override precedence order is
# qti-distro-base-user > qti-distro-user > qti-distro-base
#######################################################################################

# Honor qti-distro-user override
DISTROOVERRIDES =. "qti-distro-user:"

require conf/distro/include/qti-distro-base.inc

DISTRO_NAME = "QTI Linux distro intended for production."

DISTRO_FEATURES:append = " dm-verity"

# enabling SElinux configuration to support refpolicy-mls-generic bitbake
DISTRO_FEATURES_FILTER_NATIVE:append = "${@bb.utils.contains('DISTRO_FEATURES', 'selinux', ' selinux', '', d)}"
DISTRO_EXTRA_RDEPENDS:append = " ${@bb.utils.contains('DISTRO_FEATURES','selinux', 'packagegroup-selinux-minimal', '', d)}"
PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls-generic"
