#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-eap-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. External AP Linux Distribution
# (glibc based) having debugging capabilities. Not optimized for performance.
# Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-teleap
#  * qti-distro-teleap-debug
#
# For same variable override precedence order is
# qti-distro-teleap-debug > qti-distro-teleap > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:qti-distro-teleap:"

require conf/distro/include/qti-distro-teleap.inc

DISTRO_NAME = "QTI Linux External AP distro with debug capabilities."

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"
