#######################################################################################
#@TYPE: Distribution
#@NAME: qti-distro-xr-nodisplay-debug
#@DESCRIPTION: Qualcomm Technologies, Inc. Reference Linux Distribution
# (glibc based) for extended reality without display having debugging capabilities.
# Not optimized for performance. Allows root user access.
#
# Supported DISTROOVERRIDES are
#  * qti-distro-base
#  * qti-distro-debug
#  * qti-distro-xr-nodisplay-debug
#
# For same variable override precedence order is
# qti-distro-xr-nodisplay-debug > qti-distro-debug > qti-distro-base
#######################################################################################

# Honor qti-distro-debug override
DISTROOVERRIDES =. "qti-distro-debug:"

require conf/distro/include/qti-distro-xr-nodisplay.inc

DISTRO_NAME = "QTI Linux reference extended reality distro without display having debug capabilities."

# Set DEBUG_BUILD to use flags from DEBUG_OPTIMIZATION variable
DEBUG_BUILD = "1"

# Bring in debug utilities.
DISTRO_EXTRA_RDEPENDS += "packagegroup-qti-debug-tools"
